language: ruby

sudo: required
dist: trusty

rvm:
 - 2.3.1
env:
  - DB=sqlite
  - JOSE_CRYPTO_FALLBACK=true
  - RUBYOPT="-W0"

branches:
 only:
  - master

before_install:
  - sudo apt-get update


# uncomment this line if your project needs to run something other than `rake`:
script:
  - RACK_ENV=test bundle exec rake db:migrate
  - bundle exec rake key:generate_file
  - bundle exec rake spec
