# Copy this file to [app]/config/config_env.rb
# Replace [*] with credentials/keys/etc.
# New keys can be generated by `rake key:generate` task

config_env :development, :test do
  set 'DB_KEY', "[database encryption key in base64 url safe encoding]"
  set 'JWK256', "symmetric key"
  set 'GH_CLIENT_ID', "client id"
  set 'GH_CLIENT_SECRET', "client secret"
end
