# Copy this file to [app]/config/config_env.rb
# Replace [*] with credentials/keys/etc.
# New keys can be generated by `rake key:generate` task

config_env :development, :test do
  set 'DB_KEY', '...'
  set 'JWK256', '...'
end
